import React, { useState, useEffect, useRef } from 'react'
import { IcoPlus,IcoTrash,IcoEye,IcoEdit,IcoX,IcoCheck,IcoCloud,IcoSave,IcoDL,IcoMail,IcoAlert,IcoChevD,IcoChevU,IcoCalendar,IcoRefresh,IcoUndo,IcoUpload,IcoPrint,IcoBar,IcoPhone,IcoClock,IcoChevR,IcoBell,IcoStar,IcoUsers,IcoSun } from '../../components/icons'
import { LBL,CARD,Sect,NF,RF,PBar,RangeSelector,SortTh,ChartCanvas,TcStatusBadge } from '../../components/ui'
import { N,USD,PCT,pctNum,fmtDate,fmtTime,todayStr,monthStart,rangeStart,last30Start,repGoal,repProd,repColl,downloadCSV,printSection,newProv,newHyg,newFD,blankForm,setPath,lsGet,lsSet,lsDel,draftKey,getTcAlerts,workingDaysInMonth,workingDaysSoFar,tcChecklistPct } from '../../lib/helpers'
import { sbGet,sbPost,sbDel } from '../../lib/supabase'
import { OFFICES,RANGE_LABEL,RANGE_TITLE,TC_STATUSES,TC_STATUS_MAP,TC_PIPELINE,TC_CHECKLIST,TC_PAYMENT_METHODS,TC_FOLLOWUP_TYPES } from '../../lib/constants'

function AnalyticsPage({reports,providers,notify}){
  const [view,setView]=useState("trends");const [rangeType,setRangeType]=useState("mtd");const [customStart,setCustomStart]=useState(monthStart());const [customEnd,setCustomEnd]=useState(todayStr());const [activeOffice,setActiveOffice]=useState("all");
  const start=rangeStart(rangeType,customStart);const end=rangeType==="custom"?customEnd:todayStr();
  const all=reports.filter(r=>r.date>=start&&r.date<=end&&(activeOffice==="all"||r.office===activeOffice));
  const rl=RANGE_TITLE[rangeType];
  const doCSV=()=>{if(view==="trends"){const byDate={};all.forEach(r=>{if(!byDate[r.date])byDate[r.date]={date:r.date,prod:0,goal:0,coll:0,noShows:0,ptsSched:0,recalls:0,recallsSched:0,npCalls:0,npSched:0};const d=byDate[r.date];d.prod+=repProd(r);d.goal+=repGoal(r,providers);d.coll+=repColl(r);d.noShows+=N(r.sched?.noShows);d.ptsSched+=N(r.sched?.ptsOnSched);d.recalls+=N(r.sched?.recalls);d.recallsSched+=N(r.sched?.recallsSched);d.npCalls+=N(r.sched?.npCalls);d.npSched+=N(r.sched?.npCallsSched);});const rows=Object.values(byDate).sort((a,b)=>a.date.localeCompare(b.date)).map(d=>[d.date,d.prod,d.goal,d.prod-d.goal,PCT(d.prod,d.goal),d.coll,PCT(d.coll,d.goal),d.noShows,PCT(d.noShows,d.ptsSched),d.recalls,PCT(d.recallsSched,d.recalls),d.npCalls,PCT(d.npSched,d.npCalls)]);downloadCSV([["Date","Production","Goal","Variance","Achievement","Collections","Coll Rate","No Shows","No-Show%","Recalls","Recall%","NP Calls","NP Conv%"],...rows],`BSBD_Trends_${todayStr()}.csv`);notify("CSV downloaded!");}};
  const doPrint=()=>printSection(`BSBD — ${rl} ${view.charAt(0).toUpperCase()+view.slice(1)}`,`analytics-${view}`);
  return(
    <div style={{maxWidth:1200,margin:"0 auto",padding:"28px 20px"}}>
      <div style={{display:"flex",alignItems:"center",justifyContent:"space-between",marginBottom:20,flexWrap:"wrap",gap:12}}>
        <div><h1 style={{fontSize:24,fontWeight:800,color:"#1e293b",margin:0}}>Analytics & Reports</h1><p style={{color:"#94a3b8",fontSize:13,marginTop:4}}>{rl} · {all.length} report{all.length!==1?"s":""}</p></div>
        <div style={{display:"flex",gap:8}}><button onClick={doCSV} style={{display:"flex",alignItems:"center",gap:6,padding:"9px 18px",borderRadius:10,background:"#1d4ed8",color:"white",border:"none",fontWeight:700,fontSize:13,cursor:"pointer"}}><IcoDL size={15}/> CSV</button><button onClick={doPrint} style={{display:"flex",alignItems:"center",gap:6,padding:"9px 18px",borderRadius:10,background:"white",color:"#475569",border:"1px solid #e2e8f0",fontWeight:700,fontSize:13,cursor:"pointer"}}><IcoPrint size={15}/> PDF</button></div>
      </div>
      <RangeSelector rangeType={rangeType} setRangeType={setRangeType} customStart={customStart} setCustomStart={setCustomStart} customEnd={customEnd} setCustomEnd={setCustomEnd}/>
      <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:20,flexWrap:"wrap",gap:12}}>
        <div style={{display:"flex",gap:4,background:"white",padding:4,borderRadius:10,border:"1px solid #e2e8f0"}}>
          {[["trends","📈 Trends"],["providers","🩺 Providers"],["offices","🏢 Offices"]].map(([v,l])=>(<button key={v} onClick={()=>setView(v)} style={{padding:"8px 18px",borderRadius:8,border:"none",cursor:"pointer",fontSize:13,fontWeight:600,background:view===v?"#1d4ed8":"transparent",color:view===v?"white":"#64748b"}}>{l}</button>))}
        </div>
        <div style={{display:"flex",gap:4,background:"white",padding:4,borderRadius:10,border:"1px solid #e2e8f0"}}>
          {["all",...OFFICES].map(o=>(<button key={o} onClick={()=>setActiveOffice(o)} style={{padding:"6px 14px",borderRadius:8,border:"none",cursor:"pointer",fontSize:12,fontWeight:600,background:activeOffice===o?"#0d9488":"transparent",color:activeOffice===o?"white":"#64748b"}}>{o==="all"?"All":o}</button>))}
        </div>
      </div>
      {all.length===0?<div style={{textAlign:"center",padding:80,color:"#94a3b8",background:"white",borderRadius:12,border:"1px solid #e2e8f0"}}>No reports in this range.</div>:<>{view==="trends"&&<TrendsView reports={all} providers={providers}/>}{view==="providers"&&<ProvidersView reports={all} providers={providers}/>}{view==="offices"&&<OfficesView reports={all} providers={providers}/>}</>}
    </div>
  );
}


function TrendsView({reports,providers}){
  const [sort,setSort]=useState({field:"date",dir:"desc"});
  const byDate={};reports.forEach(r=>{if(!byDate[r.date])byDate[r.date]={date:r.date,prod:0,goal:0,coll:0,noShows:0,ptsSched:0,recalls:0,recallsSched:0,npCalls:0,npSched:0};const d=byDate[r.date];d.prod+=repProd(r);d.goal+=repGoal(r,providers);d.coll+=repColl(r);d.noShows+=N(r.sched?.noShows);d.ptsSched+=N(r.sched?.ptsOnSched);d.recalls+=N(r.sched?.recalls);d.recallsSched+=N(r.sched?.recallsSched);d.npCalls+=N(r.sched?.npCalls);d.npSched+=N(r.sched?.npCallsSched);});
  const rows=Object.values(byDate).sort((a,b)=>a.date.localeCompare(b.date));const labels=rows.map(r=>fmtDate(r.date));
  const prodChart={type:"bar",data:{labels,datasets:[{label:"Net Production",data:rows.map(r=>r.prod),backgroundColor:C.bA(.75),borderColor:C.blue,borderWidth:1,borderRadius:4},{label:"Goal",data:rows.map(r=>r.goal),backgroundColor:C.gA(.3),borderColor:C.gray,borderWidth:1,borderRadius:4}]},options:{responsive:true,plugins:{legend:{position:"top",labels:{font:{size:11}}},tooltip:{callbacks:{label:ctx=>`${ctx.dataset.label}: ${USD(ctx.raw)}`}}},scales:{y:{ticks:{callback:v=>"$"+N(v).toLocaleString()},grid:{color:"#f1f5f9"}},x:{grid:{display:false}}}}};
  const ratesChart={type:"line",data:{labels,datasets:[{label:"Recall %",data:rows.map(r=>pctNum(r.recallsSched,r.recalls)),borderColor:C.teal,backgroundColor:C.tA(.1),tension:.3,fill:true,pointRadius:4},{label:"NP Conv %",data:rows.map(r=>pctNum(r.npSched,r.npCalls)),borderColor:C.green,backgroundColor:C.gnA(.1),tension:.3,fill:true,pointRadius:4},{label:"No-Show %",data:rows.map(r=>pctNum(r.noShows,r.ptsSched)),borderColor:C.red,backgroundColor:C.rA(.1),tension:.3,fill:true,pointRadius:4}]},options:{responsive:true,plugins:{legend:{position:"top",labels:{font:{size:11}}}},scales:{y:{min:0,max:100,ticks:{callback:v=>v+"%"},grid:{color:"#f1f5f9"}},x:{grid:{display:false}}}}};
  const sorted=[...rows].sort((a,b)=>{const av=a[sort.field]??0,bv=b[sort.field]??0;return sort.dir==="asc"?(av>bv?1:-1):(av<bv?1:-1);});
  return(<div id="analytics-trends">
    <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:16,marginBottom:20}}>
      <div style={{background:"white",borderRadius:12,padding:20,border:"1px solid #e2e8f0"}}><div style={{fontSize:12,fontWeight:700,color:"#64748b",marginBottom:12}}>PRODUCTION VS GOAL — DAILY</div><ChartCanvas config={prodChart} height={260}/></div>
      <div style={{background:"white",borderRadius:12,padding:20,border:"1px solid #e2e8f0"}}><div style={{fontSize:12,fontWeight:700,color:"#64748b",marginBottom:12}}>KEY RATES — DAILY (%)</div><ChartCanvas config={ratesChart} height={260}/></div>
    </div>
    <div style={{background:"white",borderRadius:12,border:"1px solid #e2e8f0",overflow:"hidden"}}><table style={{width:"100%",borderCollapse:"collapse"}}><thead><tr>{[["date","Date"],["prod","Production"],["goal","Goal"],["coll","Collections"],["noShows","No Shows"]].map(([f,l])=>(<SortTh key={f} label={l} field={f} sort={sort} setSort={setSort}/>))}<th style={{padding:"10px 12px",textAlign:"left",fontSize:10,fontWeight:700,color:"#64748b",letterSpacing:1,borderBottom:"1px solid #e2e8f0",background:"#f8fafc"}}>ACHIEVEMENT</th><th style={{padding:"10px 12px",textAlign:"left",fontSize:10,fontWeight:700,color:"#64748b",letterSpacing:1,borderBottom:"1px solid #e2e8f0",background:"#f8fafc"}}>RECALL %</th><th style={{padding:"10px 12px",textAlign:"left",fontSize:10,fontWeight:700,color:"#64748b",letterSpacing:1,borderBottom:"1px solid #e2e8f0",background:"#f8fafc"}}>NP CONV %</th></tr></thead>
    <tbody>{sorted.map(d=>{const v=d.prod-d.goal;return(<tr key={d.date} style={{borderBottom:"1px solid #f1f5f9"}}><td style={{padding:"11px 12px",fontSize:12,fontWeight:600,color:"#1e293b",whiteSpace:"nowrap"}}>{fmtDate(d.date)}</td><td style={{padding:"11px 12px",fontSize:12,fontWeight:700}}>{USD(d.prod)}</td><td style={{padding:"11px 12px",fontSize:12,color:"#64748b"}}>{USD(d.goal)}</td><td style={{padding:"11px 12px",fontSize:12,color:"#0d9488",fontWeight:600}}>{USD(d.coll)}</td><td style={{padding:"11px 12px",fontSize:12,fontWeight:d.noShows>0?700:400,color:d.noShows>0?"#dc2626":"#475569"}}>{d.noShows}</td><td style={{padding:"11px 12px"}}><span style={{fontSize:11,fontWeight:700,padding:"2px 10px",borderRadius:99,background:v>=0?"#dcfce7":"#fee2e2",color:v>=0?"#16a34a":"#dc2626"}}>{PCT(d.prod,d.goal)}</span></td><td style={{padding:"11px 12px",fontSize:12,color:"#475569"}}>{PCT(d.recallsSched,d.recalls)}</td><td style={{padding:"11px 12px",fontSize:12,color:"#475569"}}>{PCT(d.npSched,d.npCalls)}</td></tr>);})}</tbody></table></div>
  </div>);
}


function ProvidersView({reports,providers}){
  const [sort,setSort]=useState({field:"prod",dir:"desc"});
  const byProv={};reports.forEach(r=>{r.providers.forEach(p=>{const pr=providers.find(x=>x.id===p.doctorId);if(!pr&&!p.doctorName)return;const key=pr?.id||p.doctorName;if(!byProv[key])byProv[key]={id:key,name:pr?.name||p.doctorName,goalPerDay:pr?.goal||0,office:pr?.office||"",prod:0,ptsSeen:0,npSeen:0,days:0};byProv[key].prod+=N(p.netProd);byProv[key].ptsSeen+=N(p.ptsSeen);byProv[key].npSeen+=N(p.npSeen);byProv[key].days++;});});
  const rows=Object.values(byProv).sort((a,b)=>b.prod-a.prod);const names=rows.map(p=>p.name);
  const prodChart={type:"bar",data:{labels:names,datasets:[{label:"Total Production",data:rows.map(p=>p.prod),backgroundColor:C.bA(.8),borderColor:C.blue,borderWidth:1,borderRadius:4},{label:"Total Goal",data:rows.map(p=>p.goalPerDay*p.days),backgroundColor:C.gA(.4),borderColor:C.gray,borderWidth:1,borderRadius:4}]},options:{indexAxis:"y",responsive:true,plugins:{legend:{position:"top",labels:{font:{size:11}}},tooltip:{callbacks:{label:ctx=>`${ctx.dataset.label}: ${USD(ctx.raw)}`}}},scales:{x:{ticks:{callback:v=>"$"+N(v).toLocaleString()},grid:{color:"#f1f5f9"}},y:{grid:{display:false}}}}};
  const sorted=[...rows].sort((a,b)=>{const av=a[sort.field]??0,bv=b[sort.field]??0;return sort.dir==="asc"?(av>bv?1:-1):(av<bv?1:-1);});
  return(<div id="analytics-providers">
    <div style={{background:"white",borderRadius:12,padding:20,border:"1px solid #e2e8f0",marginBottom:20}}><div style={{fontSize:12,fontWeight:700,color:"#64748b",marginBottom:12}}>PRODUCTION VS GOAL PER PROVIDER</div><ChartCanvas config={prodChart} height={Math.max(200,rows.length*50)}/></div>
    <div style={{background:"white",borderRadius:12,border:"1px solid #e2e8f0",overflow:"hidden"}}><table style={{width:"100%",borderCollapse:"collapse"}}><thead><tr><th style={{padding:"10px 12px",textAlign:"left",fontSize:10,fontWeight:700,color:"#64748b",letterSpacing:1,borderBottom:"1px solid #e2e8f0",background:"#f8fafc"}}>PROVIDER</th>{[["days","Days"],["prod","Total Prod"],["ptsSeen","Pts Seen"],["npSeen","NP Seen"]].map(([f,l])=>(<SortTh key={f} label={l} field={f} sort={sort} setSort={setSort}/>))}<th style={{padding:"10px 12px",textAlign:"left",fontSize:10,fontWeight:700,color:"#64748b",letterSpacing:1,borderBottom:"1px solid #e2e8f0",background:"#f8fafc"}}>ACHIEVEMENT</th><th style={{padding:"10px 12px",textAlign:"left",fontSize:10,fontWeight:700,color:"#64748b",letterSpacing:1,borderBottom:"1px solid #e2e8f0",background:"#f8fafc"}}>AVG / DAY</th></tr></thead>
    <tbody>{sorted.map(p=>{const totalGoal=p.goalPerDay*p.days;const ach=pctNum(p.prod,totalGoal);return(<tr key={p.id} style={{borderBottom:"1px solid #f1f5f9"}}><td style={{padding:"11px 12px"}}><div style={{fontSize:13,fontWeight:700,color:"#1e293b"}}>{p.name}</div><div style={{fontSize:11,color:"#94a3b8"}}>{p.office}</div></td><td style={{padding:"11px 12px",fontSize:12,color:"#475569",textAlign:"center"}}>{p.days}</td><td style={{padding:"11px 12px",fontSize:12,fontWeight:700}}>{USD(p.prod)}</td><td style={{padding:"11px 12px",fontSize:12,color:"#475569",textAlign:"center"}}>{p.ptsSeen}</td><td style={{padding:"11px 12px",fontSize:12,color:"#475569",textAlign:"center"}}>{p.npSeen}</td><td style={{padding:"11px 12px"}}><span style={{fontSize:11,fontWeight:700,padding:"2px 10px",borderRadius:99,background:ach>=100?"#dcfce7":ach>=75?"#fef3c7":"#fee2e2",color:ach>=100?"#16a34a":ach>=75?"#d97706":"#dc2626"}}>{PCT(p.prod,totalGoal)}</span></td><td style={{padding:"11px 12px",fontSize:12,color:"#475569"}}>{p.days>0?USD(p.prod/p.days):"-"}</td></tr>);})}</tbody></table></div>
  </div>);
}


function OfficesView({reports,providers}){
  const [sort,setSort]=useState({field:"prod",dir:"desc"});
  const byOffice={};reports.forEach(r=>{if(!byOffice[r.office])byOffice[r.office]={office:r.office,count:0,prod:0,goal:0,coll:0,noShows:0,ptsSched:0,recalls:0,recallsSched:0,npCalls:0,npSched:0};const d=byOffice[r.office];d.count++;d.prod+=repProd(r);d.goal+=repGoal(r,providers);d.coll+=repColl(r);d.noShows+=N(r.sched?.noShows);d.ptsSched+=N(r.sched?.ptsOnSched);d.recalls+=N(r.sched?.recalls);d.recallsSched+=N(r.sched?.recallsSched);d.npCalls+=N(r.sched?.npCalls);d.npSched+=N(r.sched?.npCallsSched);});
  const rows=Object.values(byOffice);const names=rows.map(o=>o.office);const palette=[C.bA(.8),C.tA(.8),"rgba(124,58,237,.8)",C.amber+"cc"];
  const prodChart={type:"bar",data:{labels:names,datasets:[{label:"Net Production",data:rows.map(o=>o.prod),backgroundColor:rows.map((_,i)=>palette[i%4]),borderColor:rows.map((_,i)=>[C.blue,C.teal,"#7c3aed",C.amber][i%4]),borderWidth:1,borderRadius:4},{label:"Goal",data:rows.map(o=>o.goal),backgroundColor:C.gA(.3),borderColor:C.gray,borderWidth:1,borderRadius:4}]},options:{responsive:true,plugins:{legend:{position:"top",labels:{font:{size:11}}},tooltip:{callbacks:{label:ctx=>`${ctx.dataset.label}: ${USD(ctx.raw)}`}}},scales:{y:{ticks:{callback:v=>"$"+N(v).toLocaleString()},grid:{color:"#f1f5f9"}},x:{grid:{display:false}}}}};
  const ratesChart={type:"bar",data:{labels:names,datasets:[{label:"Recall %",data:rows.map(o=>pctNum(o.recallsSched,o.recalls)),backgroundColor:C.tA(.8),borderRadius:4},{label:"NP Conv %",data:rows.map(o=>pctNum(o.npSched,o.npCalls)),backgroundColor:C.gnA(.8),borderRadius:4},{label:"No-Show %",data:rows.map(o=>pctNum(o.noShows,o.ptsSched)),backgroundColor:C.rA(.7),borderRadius:4}]},options:{responsive:true,plugins:{legend:{position:"top",labels:{font:{size:11}}},tooltip:{callbacks:{label:ctx=>`${ctx.dataset.label}: ${ctx.raw.toFixed(1)}%`}}},scales:{y:{min:0,max:100,ticks:{callback:v=>v+"%"},grid:{color:"#f1f5f9"}},x:{grid:{display:false}}}}};
  const sorted=[...rows].sort((a,b)=>{const av=a[sort.field]??0,bv=b[sort.field]??0;return sort.dir==="asc"?(av>bv?1:-1):(av<bv?1:-1);});
  return(<div id="analytics-offices">
    <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:16,marginBottom:20}}>
      <div style={{background:"white",borderRadius:12,padding:20,border:"1px solid #e2e8f0"}}><div style={{fontSize:12,fontWeight:700,color:"#64748b",marginBottom:12}}>PRODUCTION BY OFFICE</div><ChartCanvas config={prodChart} height={260}/></div>
      <div style={{background:"white",borderRadius:12,padding:20,border:"1px solid #e2e8f0"}}><div style={{fontSize:12,fontWeight:700,color:"#64748b",marginBottom:12}}>KEY RATES BY OFFICE</div><ChartCanvas config={ratesChart} height={260}/></div>
    </div>
    <div style={{background:"white",borderRadius:12,border:"1px solid #e2e8f0",overflow:"hidden"}}><table style={{width:"100%",borderCollapse:"collapse"}}><thead><tr><th style={{padding:"10px 12px",textAlign:"left",fontSize:10,fontWeight:700,color:"#64748b",letterSpacing:1,borderBottom:"1px solid #e2e8f0",background:"#f8fafc"}}>OFFICE</th>{[["count","Reports"],["prod","Production"],["goal","Goal"],["coll","Collections"],["noShows","No Shows"]].map(([f,l])=>(<SortTh key={f} label={l} field={f} sort={sort} setSort={setSort}/>))}<th style={{padding:"10px 12px",textAlign:"left",fontSize:10,fontWeight:700,color:"#64748b",letterSpacing:1,borderBottom:"1px solid #e2e8f0",background:"#f8fafc"}}>ACHIEVEMENT</th><th style={{padding:"10px 12px",textAlign:"left",fontSize:10,fontWeight:700,color:"#64748b",letterSpacing:1,borderBottom:"1px solid #e2e8f0",background:"#f8fafc"}}>RECALL %</th><th style={{padding:"10px 12px",textAlign:"left",fontSize:10,fontWeight:700,color:"#64748b",letterSpacing:1,borderBottom:"1px solid #e2e8f0",background:"#f8fafc"}}>COLL RATE</th></tr></thead>
    <tbody>{sorted.map(o=>{const ach=pctNum(o.prod,o.goal);return(<tr key={o.office} style={{borderBottom:"1px solid #f1f5f9"}}><td style={{padding:"11px 12px",fontSize:13,fontWeight:700,color:"#1e293b"}}>{o.office}</td><td style={{padding:"11px 12px",fontSize:12,color:"#475569",textAlign:"center"}}>{o.count}</td><td style={{padding:"11px 12px",fontSize:12,fontWeight:700}}>{USD(o.prod)}</td><td style={{padding:"11px 12px",fontSize:12,color:"#64748b"}}>{USD(o.goal)}</td><td style={{padding:"11px 12px",fontSize:12,color:"#0d9488",fontWeight:600}}>{USD(o.coll)}</td><td style={{padding:"11px 12px",fontSize:12,fontWeight:o.noShows>0?700:400,color:o.noShows>0?"#dc2626":"#475569",textAlign:"center"}}>{o.noShows}</td><td style={{padding:"11px 12px"}}><span style={{fontSize:11,fontWeight:700,padding:"2px 10px",borderRadius:99,background:ach>=100?"#dcfce7":ach>=75?"#fef3c7":"#fee2e2",color:ach>=100?"#16a34a":ach>=75?"#d97706":"#dc2626"}}>{PCT(o.prod,o.goal)}</span></td><td style={{padding:"11px 12px",fontSize:12,color:"#475569"}}>{PCT(o.recallsSched,o.recalls)}</td><td style={{padding:"11px 12px",fontSize:12,color:"#475569"}}>{PCT(o.coll,o.goal)}</td></tr>);})}</tbody></table></div>
  </div>);
}

// ── Detail View ────────────────────────────────────────────────────────────


export default AnalyticsPage
